config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"
  resources :posts do
	  resource :favorites, only: [:create, :destroy]
	  resource :post_comments, only: [:create, :destroy]
  end
  get 'users/top' => 'users#top'
  get 'users/exit' => 'users#exit'
  resources :users
  resources :rankings
  get'/search' => 'concerns#search'
  resources :concerns do
    resource :concern_comments, only:[:create, :destroy]
  end
  get 'tags/:tag', to: 'tags#index', as: :tag
  resources :recommendations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concern.rb
class Concern < ApplicationRecord
	attachment :image
	belongs_to :user
	has_many :concern_comments, dependent: :destroy

	def self.search(search)
		if search
			Concern.where(['body LIKE ? OR title LIKE ?', "%#{search}%" , "%#{search}%"])
		else
			Concern.all
		end
	end
end

app/models/concern_comment.rb
class ConcernComment < ApplicationRecord
	belongs_to :user
	belongs_to :concern
	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	attachment :image
	acts_as_taggable
	has_many :post_comments,dependent: :destroy
	has_many :favorites,dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	mount_uploader :video, VideoUploader
	validates :title, presence: true
	validates :body, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :comment, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :concerns, dependent: :destroy
  has_many :concerns_comments, dependent: :destroy
  attachment :profile_image
  attachment :header_image
  validates :username, presence: true
end

app/controllers/concerns_controller.rb
class ConcernsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]
	PER = 10

	def new
		@concern = Concern.new
	end

	def index
		@concerns = Concern.page(params[:page]).per(PER)
	end

	def show
		@concern = Concern.find(params[:id])
		@concern_comment = ConcernComment.new
	end

	def search
		@concerns = Concern.search(params[:search]).page(params[:page]).per(PER)
	end

	def create
		@concern = Concern.new(concern_params)
		@concern.user_id = current_user.id
		@concern.save
		redirect_to search_path
	end

	def destroy
		@concern = Concern.find(params[:id])
		@concern.destroy
		redirect_to search_path
	end

 private
 def concern_params
 	params.require(:concern).permit(:title, :body, :image)
 end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	PER = 8
	def index
		@posts = Post.page(params[:page]).per(PER)
		@dailyRanks = Post.find(Favorite.where(created_at:1.days.ago..Time.now).group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
	end
	def show
		@post = Post.find(params[:id])
		@post_comment = PostComment.new
		@post_comments = PostComment.all
	end
	def new
		@post = Post.new
	end
	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		if @post.save
		   redirect_to posts_path
		else
		   render :new
		end
	end
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

	private
	    def post_params
	        params.require(:post).permit(:title, :image, :body, :tag_list,:video)
	    end

end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
	def index
		@dailyRanks = Post.find(Favorite.where(created_at:1.days.ago..Time.now).group(:post_id).order('count(post_id) desc').limit(10).pluck(:post_id))
		@weeklyRanks = Post.find(Favorite.where(created_at:1.weeks.ago..Time.now).group(:post_id).order('count(post_id) desc').limit(10).pluck(:post_id))
		@monthlyRanks = Post.find(Favorite.where(created_at:1.months.ago..Time.now).group(:post_id).order('count(post_id) desc').limit(10).pluck(:post_id))
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		if params[:tag]
			@tag = Tag.where(name: params[:tag]).first
			@posts = Post.tagged_with(params[:tag])
		else
			@posts = Post.all
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def top
		@user = User.find(current_user.id)
	end
	def index
	end
	def show
		@user = User.find(params[:id])
	end
	def edit
		@user = User.find(current_user.id)
	end
	def update
		@user = User.find(current_user.id)
			if  @user.update(user_params)
				redirect_to user_path
			else
				render :edit
			end
end
	private
	def user_params
		params.require(:user).permit(:username, :profile_image, :header_image, :email, :password, :introduction )
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerns_helper.rb
module ConcernsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/concerns/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<h2>相談掲示板へ相談する</h2>
				<%= form_for(@concern,url: concerns_path) do |f| %>
					<h4>相談タイトル</h4>
					<%= f.text_field :title %>
					<%= f.attachment_field :image %>
					<h4>内容</h4>
					<%= f.text_area :body, class:"form-control", rows:"10", placeholder:"本文" , size: "50x30" %>
					<%= f.submit '送信' %>
				<% end %>
		</div>
	</div>
</div>

app/views/concerns/search.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<p>検索</p>
			<%= form_tag(search_path,:method => 'get') do %>
			  <%= text_field_tag :search %>
			  <%= submit_tag '検索', :name => nil %>
			<% end %>
			<div class="concern">
				<span>相談一覧</span>
				<span><%= link_to "相談する",new_concern_path %></span>
			</div>



			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<% @concerns.each do |concern| %><!--コメント機能のView -->
					<tbody>
						<tr>
							<th><%= link_to concern.title, concern %></th>
							<th><%= concern.created_at.strftime('%Y/%m/%d') %></th>
								<% if concern.user == current_user %>
									<th><%= link_to "削除",concern_path(concern),method: :delete %></th>
								<% end %>
						</tr>
					</tbody>
				<% end %>
			</table>

			<%= paginate @concerns %>
		</div>
	</div>
</div>

app/views/concerns/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<% if @concern_comment.errors.any? %>
			  <div id="error_explanation" class="alert alert-danger">
			    <ul>
			      <% @concern_comment.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			      <% end %>
			    </ul>
			  </div>
			<% end %>

			<h3>質問タイトル：<%= @concern.title %></h3>
			<h5>質問内容：<%= @concern.body %></h5>
			<%= attachment_image_tag @concern,:image, :fill, 150, 150, class: "profile-thumb", fallback: "" %>
			<div>投稿主：<%= @concern.user.username %></div>

			<table class="table">
				<thead>
					<tr>
						<th>ユーザー名</th>
						<th>コメント<%= @concern.concern_comments.count %>件</th>
						<th>コメント日時</th>
					</tr>
				</thead>
				<% @concern.concern_comments.each do |concern_comment| %><!--コメント機能のView -->
					<tbody>
						<tr>
							<th><%= concern_comment.user.username %></th>
							<th><%= concern_comment.comment %></th>
							<th><%= concern_comment.created_at.strftime('%Y/%m/%d') %></th>
						</tr>
					</tbody>
				<% end %>
			</table>

			<%= form_for [@concern, @concern_comment] do |f| %> <!--コメント投稿フォーム-->
				<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
				<%= f.submit "送信する" %>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
		<h2 class="best"><i class="fas fa-dog"></i> 今日のBEST3 <i class="fas fa-dog"></i></h2>
			<% if @dailyRanks.present? %>
				<% @dailyRanks.each do |post| %>
					<div class="col-sm-4">
						<div class="panel panel-default">
							<div class="panel-heading">
								<%= attachment_image_tag post,:image, :fill, 330, 330, class: "profile-thumb", fallback: "" %>
							</div>
							<div class="panel-body">
								<div>タイトル: <%= link_to post.title , post_path(post.id) %></div>
								<div>投稿者: <%= link_to post.user.username,user_path(post.user.id) %></div>
								<div><i class="fa fa-heart-o" aria-hidden="true"></i> <%= post.favorites.count %></div>
								<div><%= post.post_comments.count %>件のコメント</div>
							</div>
						</div>
					</div>
				<% end %>
			<% else %>
				<h2>いいね集計中です</h2>
			<% end %>
	</div>

	<div class="row">
		<h2 class="new"><i class="fas fa-paw"></i> 新着投稿 <i class="fas fa-paw"></i></h2>
			<% if user_signed_in? %>
				<p class="pos"><%= link_to "投稿する",new_post_path %></p>
			<% else %>
				<P><%= link_to "ログイン",new_user_session_path  %>すると投稿ができるようになります</P>
			<% end %>

			<% @posts.each do |post| %>
				<div class="col-sm-3">
					<div class="panel panel-default">
						<div class="panel-heading">
							<%= attachment_image_tag post,:image, :fill, 230, 230, class: "profile-thumb", fallback: "" %>
								<% if post.video_url.present? %>
									<%= video_tag post.video_url.to_s,loop: true, controls: true, width: 230,  id: "mv" %>
								<% end %>
						</div>
						<div class="panel-body">
							<div>タイトル: <%= link_to post.title , post_path(post.id) %></div>
							<div>投稿者: <%= link_to post.user.username,user_path(post.user.id) %></div>
							<div><i class="fa fa-heart-o" aria-hidden="true"></i> <%= post.favorites.count %></div>
							<div><%= post.post_comments.count %>件のコメント</div>
						</div>
					</div>
				</div>
			<% end %>
	</div>

	<%= paginate @posts %>

	<div class="row">
		<div class="col-som-12">
			<h2 class="suggest">管理人おすすめ動画</h2>
				<div id="sample"></div>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<% if @post.errors.any? %>
		  <div id="error_explanation" class="alert alert-danger">
		    <ul>
		      <% @post.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		    </ul>
		  </div>
		<% end %>

		<h2>新規投稿</h2>
			<div class="new-post">
				<%= form_for(@post,url: posts_path) do |f| %>
					<%= f.text_field :title, class:"form-control", placeholder:"タイトル" %>
					画像<%= f.attachment_field :image %>
					動画<%= f.file_field :video %>
					<%= f.text_area :body, class:"form-control", rows:"10", placeholder:"本文" %>
					<div class='field'>
					    <%= f.label :"タグを追加" %>
					    <%= f.text_field :tag_list %> ,カンマ区切りで複数のタグ付けができます　（例  柴犬,秋田犬
					</div>
					<%= f.submit "投稿する" %>
				<% end %>
			</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">

			<div show-image><%= attachment_image_tag @post,:image, :fill, 500, 500, class: "profile-thumb", fallback: "" %></div>
			<% if @post.video_url.present? %>
				<%= video_tag @post.video_url.to_s,loop: true, controls: true, width: 500,  id: "mv" %>
			<% end %>
			<h2><%= @post.title %></h2>
			<h5><%= @post.body %></h5>
			<div>投稿者:<%= @post.user.username %></div>
			<p>タグ: <%= raw(@post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) %></p>

		<% if user_signed_in? %>
			<% if @post.favorited_by?(current_user) %> <!--いいねボタン -->
				<%= link_to post_favorites_path(@post),method: :delete do %>
					<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
					<%= @post.favorites.count %> いいね
				<% end %>
			<% else %>
				<%= link_to post_favorites_path(@post),method: :post do %>
					<i class="fa fa-heart-o" aria-hidden="true"></i>
					<%= @post.favorites.count %>いいね
				<% end %>
			<% end %>
		<% end %>

			<%= @post.created_at.strftime('%Y/%m/%d') %>

			<% if @post.user == current_user %>
				<%= link_to "削除",post_path(@post), method: :delete %>
			<% end %>

			<% if @post_comment.errors.any? %>
			  <div id="error_explanation" class="alert alert-danger">
			    <ul>
			      <% @post_comment.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			      <% end %>
			    </ul>
			  </div>
			<% end %>



			<table class="table">
				<thead>
					<tr>
						<th>ユーザー名</th>
						<th>コメント<%= @post.post_comments.count %>件</th>
						<th>コメント日</th>
					</tr>
				</thead>
				<% @post.post_comments.each do |post_comment| %><!--コメント機能のView -->
					<tbody>
						<tr>
							<th><%= post_comment.user.username %></th>
							<th><%= post_comment.comment %></th>
							<th><%= post_comment.created_at.strftime('%Y/%m/%d') %></th>
						</tr>
					</tbody>
				<% end %>
			</table>

			<%= form_for [@post, @post_comment] do |f| %>
				<% if user_signed_in? %>
				    <%= f.hidden_field :user_id , :value => current_user.id %>
				    <%= f.hidden_field :post_id , :value => @post.id %>
			    <% end %>
				<%= f.text_area :comment,class:"form-control",placeholder:"コメントをここに" %>
				<%= f.submit "送信する" %>
			<% end %>
		</div>
	</div>
</div>

app/views/tags/index.html.erb
<h2>タグ: <%= @tag.name %>の検索結果 </h2>

<% @posts.each do |post| %>
	<div class="col-sm-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<%= attachment_image_tag post,:image, :fill, 280, 230, class: "profile-thumb", fallback: "" %>
					<% if post.video_url.present? %>
						<%= video_tag post.video_url.to_s,loop: true, controls: true, width: 230,  id: "mv" %>
					<% end %>
			</div>
			<div class="panel-body">
				<div>タイトル: <%= link_to post.title , post_path(post.id) %></div>
				<div>投稿者: <%= link_to post.user.username,user_path(post.user.id) %></div>
			</div>
		</div>
	</div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
      <h2>プロフィール編集</h2>
          <% if @user.errors.any? %>
            <div id="error_explanation" class="alert alert-danger">
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <%= form_for(@user) do |f| %>
          		<div>ユーザー名<%= f.text_field :username,autofocus:true,id:"inputName" %></div>
          　　	<div>プロフィール画像<%= f.attachment_field :profile_image %></div>
          		<div>ヘッダー画像<%= f.attachment_field :header_image %></div>
          		<div>自己紹介<%= f.text_area :introduction %></div>
          		<%= f.submit "保存" %>
          	<% end %>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログインはこちらから", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規会員登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れですか?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h2 class="name"><%= @user.username %>さんのプロフィール</h2>

<div class="profile">
	<div class="profile-image"><%= attachment_image_tag @user,:profile_image, :fill, 150, 150, class: "radius", fallback: "" %></div>
	<div class="header-image"><%= attachment_image_tag @user,:header_image, :fill, 500,300, class: "profile-thumb" %></div>


	<div>自己紹介：<%= @user.introduction %></div>
		<% if @user == current_user %>
			<div><%= link_to "プロフィール編集", edit_user_path(@user) %></div>
		<% end %>
</div>