config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"
  resources :posts do
	  resource :favorites, only: [:create, :destroy]
	  resource :post_comments, only: [:create, :destroy]
  end
  get 'users/top' => 'users#top'
  get 'users/exit' => 'users#exit'
  resources :users
  resources :rankings
  get'/search' => 'concerns#search'
  resources :concerns do
    resource :concern_comments, only:[:create, :destroy]
  end
  get 'tags/:tag', to: 'tags#index', as: :tag
  resources :recommendations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concern.rb
class Concern < ApplicationRecord
	attachment :image
	belongs_to :user
	has_many :concern_comments, dependent: :destroy

	def self.search(search)
		if search
			Concern.where(['body LIKE ? OR title LIKE ?', "%#{search}%" , "%#{search}%"])
		else
			Concern.all
		end
	end
end

app/models/concern_comment.rb
class ConcernComment < ApplicationRecord
	belongs_to :user
	belongs_to :concern
	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	attachment :image
	acts_as_taggable
	has_many :post_comments,dependent: :destroy
	has_many :favorites,dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	mount_uploader :video, VideoUploader
	validates :title, presence: true
	validates :body, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :comment, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :concerns, dependent: :destroy
  has_many :concerns_comments, dependent: :destroy
  attachment :profile_image
  attachment :header_image
  validates :username, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	PER = 8
	def index
		@posts = Post.page(params[:page]).per(PER)
		@dailyRanks = Post.find(Favorite.where(created_at:1.days.ago..Time.now).group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
	end
	def show
		@post = Post.find(params[:id])
		@post_comment = PostComment.new
		@post_comments = PostComment.all
	end
	def new
		@post = Post.new
	end
	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		if @post.save
		   redirect_to posts_path
		else
		   render :new
		end
	end
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

	private
	    def post_params
	        params.require(:post).permit(:title, :image, :body, :tag_list,:video)
	    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		if params[:tag]
			@tag = Tag.where(name: params[:tag]).first
			@posts = Post.tagged_with(params[:tag])
		else
			@posts = Post.all
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def top
		@user = User.find(current_user.id)
	end
	def index
	end
	def show
		@user = User.find(params[:id])
	end
	def edit
		@user = User.find(current_user.id)
	end
	def update
		@user = User.find(current_user.id)
			if  @user.update(user_params)
				redirect_to user_path
			else
				render :edit
			end
end
	private
	def user_params
		params.require(:user).permit(:username, :profile_image, :header_image, :email, :password, :introduction )
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerns_helper.rb
module ConcernsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CPPT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/afed6a0c47.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="sample.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

  <body>
    <header>
      <nav>
        <ul id="nav">
           <li><i class="fas fa-home"></i><%= link_to "HOME",posts_path %>
             <%if user_signed_in? %> <!-- ユーザーがログインしている時 -->
                <li><i class="fas fa-trophy"></i><%= link_to "ランキング", rankings_path %>
                <li><i class="fas fa-bone"></i><%= link_to "相談掲示板", search_path %>
                <li><i class="fas fa-user"></i><%= link_to current_user.username, user_path(current_user.id) %>さん
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %><i class="fas fa-sign-out-alt"></i>
            <% else %>             <!--ユーザーがログインしていない時 -->
                <li><i class="fas fa-trophy"></i><%= link_to "ランキング", rankings_path %>
                <li><%= link_to "相談掲示板", search_path %>
                <li><%= link_to "新規会員登録", new_user_registration_path %>
                <li><%= link_to "ログイン",new_user_session_path  %>
            <% end %>
        </ul>
      </nav>
    </header>
    <%= yield %>
    <footer>
    </footer>
  </body>
</html>